"""add embeddings to document chunks

Revision ID: cd35aa9b49d3
Revises: 3f4bf8938cca
Create Date: 2026-09-26 16:50:18.161358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = 'cd35aa9b49d3'
down_revision: Union[str, Sequence[str], None] = '3f4bf8938cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'document_chunks',
        sa.Column(
            'embedding',
            VECTOR(384),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
